export const projects = [
  {
    id: "01",
    title: "Annapurna Collections",
    slug: "annapurna-collections",
    tier: 1,
    status: "PRODUCTION",
    metric: "Zero infra cost",
    description: "Luxury heritage jewelry storefront and custom CMS.",
    stack: ["Next.js", "Sanity", "Razorpay"],
    solo: true,
    untold: false,
    image: "/assets/products/annapurna.png",
    problem: "A heritage jewelry brand was losing the stories behind every piece to generic Shopify templates.",
    decision: "Built a custom CMS that treats each piece like a museum exhibit — provenance, craft, and context before the buy button.",
    outcome: "Every product page now reads like a gallery label. Conversion followed story.",
    connections: {
      tech: ["03", "08"],
      problem: ["06"],
      outcome: ["04"],
    },
  },
  {
    id: "02",
    title: "DOC AI",
    slug: "doc-ai",
    tier: 1,
    status: "FUNCTIONAL",
    metric: "14 templates",
    description: "AI document formatting workstation with strict QA validation.",
    stack: ["React", "Gemini", "Mermaid.js"],
    solo: true,
    untold: true,
    image: "/assets/products/docai.png",
    problem: "Spending 40 minutes formatting documents that should take 4. Every BRD, every spec doc — same pain.",
    decision: "Instead of learning Word shortcuts, built an AI workstation that understands document structure and enforces QA rules.",
    outcome: "14 templates. Documents that used to take hours now take minutes. Nobody asked for it. Everyone uses it.",
    connections: {
      tech: [],
      problem: ["04", "10"],
      outcome: ["04", "05"],
    },
  },
  {
    id: "03",
    title: "DPMUMS",
    slug: "dpmums",
    tier: 1,
    status: "TESTING",
    metric: "152 employees",
    description: "Government-scale ERP with GPS geofencing and real-time attendance.",
    stack: ["Next.js", "Supabase", "Pusher"],
    solo: true,
    untold: false,
    image: "/assets/products/dpmums.png",
    problem: "152 employees across 8 districts. Attendance tracked on paper. Payroll took 3 weeks.",
    decision: "GPS geofencing plus photo verification. Real-time sync even on 2G. Built for the worst connectivity, not the best.",
    outcome: "Payroll from 3 weeks to 3 hours. 152 employees. Zero infrastructure cost. Still in testing because government moves slow.",
    connections: {
      tech: ["01", "08"],
      problem: ["05", "09"],
      outcome: ["05"],
    },
  },
  {
    id: "04",
    title: "Reports Automation",
    slug: "reports-automation",
    tier: 1,
    status: "PRODUCTION",
    metric: "v102 stable",
    description: "Autonomous field reporting engine delivering role-based HTML dashboards.",
    stack: ["Apps Script", "Gmail API", "Webhooks"],
    solo: true,
    untold: true,
    image: "/assets/products/reports.png",
    problem: "Field workers sending photos on WhatsApp. Managers manually compiling reports. 2 hours every evening, every day.",
    decision: "Automated the entire pipeline — data collection, validation, HTML dashboard generation, email delivery. Zero manual steps.",
    outcome: "v102. Running autonomously for months. 13 org chart roles receiving custom reports. Nobody manages it anymore.",
    connections: {
      tech: ["05", "06", "07", "09", "10"],
      problem: ["02", "05"],
      outcome: ["01", "02"],
    },
  },
  {
    id: "05",
    title: "Field Reporter",
    slug: "field-reporter",
    tier: 2,
    status: "FUNCTIONAL",
    metric: "8 districts",
    description: "T-Fiber telecom workforce app with strict 3-phase engine.",
    stack: ["Apps Script", "Maps API", "Vanilla JS"],
    solo: true,
    untold: true,
    image: "/assets/products/field-reporter.png",
    problem: "Telecom field workers across 8 districts. No visibility into who was where, doing what.",
    decision: "3-phase reporting engine: check-in, work log, check-out. Location-verified. Built on Google's infra because the budget was zero.",
    outcome: "8 districts covered. Real-time workforce visibility. The system that proved I could build for scale.",
    connections: {
      tech: ["04", "06", "07", "09", "10"],
      problem: ["03", "04"],
      outcome: ["03", "04"],
    },
  },
  {
    id: "06",
    title: "Vantage OS",
    slug: "vantage-os",
    tier: 2,
    status: "FUNCTIONAL",
    metric: "3 contexts",
    description: "Multi-context finance tracker with Udhaar debt-splitting logic.",
    stack: ["React", "Firebase", "Apps Script"],
    solo: true,
    untold: false,
    image: "/assets/products/vantage.png",
    problem: "Every finance app assumes one life. I have three — personal, family business, and side projects.",
    decision: "Multi-context architecture with Udhaar (informal debt) logic that Indian households actually use.",
    outcome: "3 contexts. Debt splitting that makes sense for how money actually moves in Indian families.",
    connections: {
      tech: ["04", "05", "07", "09", "10"],
      problem: ["01"],
      outcome: [],
    },
  },
  {
    id: "07",
    title: "Span Finder Pro",
    slug: "span-finder-pro",
    tier: 2,
    status: "FUNCTIONAL",
    metric: "0.005 deg precision",
    description: "Geospatial telecom infra lookup with tile-based spatial indexing.",
    stack: ["Apps Script", "Leaflet", "GeoJSON"],
    solo: true,
    untold: false,
    image: "/assets/products/spanfinder.png",
    problem: "Finding the nearest telecom tower required calling 5 people and waiting 2 days.",
    decision: "Tile-based spatial indexing on a map. 0.005 degree precision. Query by location, get answers in seconds.",
    outcome: "What took 2 days now takes 2 seconds. Built for field engineers who do not have time for bureaucracy.",
    connections: {
      tech: ["04", "05", "06", "09", "10"],
      problem: ["05"],
      outcome: ["05"],
    },
  },
  {
    id: "08",
    title: "GlobusIT ERP",
    slug: "globus-erp",
    tier: 3,
    status: "IN DEVELOPMENT",
    metric: "Task intent engine",
    description: "Internal organizational platform with hierarchical org-chart logic.",
    stack: ["Next.js", "Prisma", "TanStack"],
    solo: true,
    untold: false,
    image: "/assets/products/erp.png",
    problem: "Internal tools that do not talk to each other. Org charts that are PDFs. Task assignment that happens on WhatsApp.",
    decision: "Task Intent Engine — the system understands what needs to happen based on role, hierarchy, and context.",
    outcome: "In development. Will replace 4 separate tools with one platform. Org chart logic baked into every interaction.",
    connections: {
      tech: ["01", "03"],
      problem: ["09"],
      outcome: ["09"],
    },
  },
  {
    id: "09",
    title: "BSEC Recruitment",
    slug: "bsec-recruitment",
    tier: 3,
    status: "FUNCTIONAL",
    metric: "64 positions placed",
    description: "Relational CRM built on Google Sheets before the Next.js migration.",
    stack: ["Apps Script", "Bootstrap"],
    solo: true,
    untold: false,
    image: "/assets/products/bsec.png",
    problem: "Recruitment tracking on disconnected spreadsheets. No pipeline visibility. Candidates falling through cracks.",
    decision: "Built a relational CRM on Google Sheets — the tool they already had. Made it work before asking for a tech stack.",
    outcome: "64 positions placed. Pipeline visibility for the first time. Proved the concept. Now migrating to Next.js.",
    connections: {
      tech: ["04", "05", "06", "07", "10"],
      problem: ["03", "08"],
      outcome: ["08"],
    },
  },
  {
    id: "10",
    title: "Script Collection",
    slug: "utility-collection",
    tier: 4,
    status: "ARCHIVE",
    metric: "Foundational",
    description: "Provenance archive of the original scripts that started it all.",
    stack: ["Apps Script", "Python"],
    solo: true,
    untold: true,
    image: "/assets/products/scripts.png",
    problem: "Every builder has a graveyard of early scripts. Mine were the seeds of everything that followed.",
    decision: "Archived instead of deleted. Every script tells a story about a problem I noticed and chose to solve.",
    outcome: "The foundation. These scripts became the systems. The systems became the products. The products became the proof.",
    connections: {
      tech: ["04", "05", "06", "07", "09"],
      problem: ["02"],
      outcome: [],
    },
  },
];

export const personalInfo = {
  name: "Anvith Reddy Rondla",
  title: "Product Manager and Systems Builder",
  location: "Hyderabad, India",
  email: "anvithreddy.rondla@gmail.com",
  linkedin: "#",
  github: "#",
  twitter: "#",
  currently: {
    building: "DPMUMS v1.0 — GPS geofencing and real-time attendance",
    reading: "Building High Growth Products",
    thinking: "AI Agents for Field Operations",
    lastDeploy: "Reports Automation v102",
  },
  stats: {
    products: 10,
    states: 2,
    infraCost: "Zero",
    teamSize: 0,
    employeesTracked: 152,
    positionsPlaced: 64,
    districts: 8,
    orgChartRoles: 13,
    pingsPerMonth: "1.2M+",
  },
  philosophy: [
    "Every product I ship starts with a BRD. Not because I was told to.",
    "I learned Next.js by deploying it to a state government contract.",
    "I use AI to move faster, not to skip thinking.",
    "Everything I have ever built still runs in production.",
  ],
  story:
    "Joined GlobusIT as a Data Analyst. Watched field workers send data on WhatsApp. Watched managers compile reports manually. Watched the same problems repeat every week. Built a system to fix it — unprompted, on my own time. Got promoted to Junior Product Manager in two months. Have not stopped building since.",
};
