export const projects = [
  {
    id: "01",
    title: "Annapurna Collections",
    slug: "annapurna-collections",
    tier: 1,
    status: "PRODUCTION",
    metric: "Zero infra cost",
    description: "Luxury heritage jewelry storefront and custom CMS.",
    stack: ["Next.js", "Sanity", "Razorpay"],
    solo: true,
    untold: false,
    pattern: "pattern-annapurna",
    monogram: "AC",
    problem: "A heritage jewelry brand required a custom interface to capture the unique provenance of its artisanal creations, which were restricted by generic commerce platforms.",
    decision: "Architected a bespoke CMS that curates items like digital museum exhibits, incorporating historical provenance, design craft, and context prior to purchase.",
    outcome: "Product pages were transformed into highly engaging gallery experiences, successfully driving brand conversion through rich narrative.",
    connections: {
      tech: ["03", "08"],
      problem: ["06"],
      outcome: ["04"],
    },
  },
  {
    id: "02",
    title: "DOC AI",
    slug: "doc-ai",
    tier: 1,
    status: "FUNCTIONAL",
    metric: "14 templates",
    description: "AI powered document formatting workstation with strict QA validation.",
    stack: ["React", "Gemini", "Mermaid.js"],
    solo: true,
    untold: true,
    pattern: "pattern-docai",
    monogram: "DA",
    problem: "Document preparation, such as writing business requirements and specifications, suffered from repetitive manual formatting workflows, consuming valuable cycles.",
    decision: "Developed an AI powered markdown workstation that programmatically structures documents and enforces automated quality assurance guidelines.",
    outcome: "Integrated 14 standardized enterprise templates, optimizing document creation workflows from hours to minutes with high organizational adoption.",
    connections: {
      tech: [],
      problem: ["04", "10"],
      outcome: ["04", "05"],
    },
  },
  {
    id: "03",
    title: "DPMUMS",
    slug: "dpmums",
    tier: 1,
    status: "TESTING",
    metric: "152 employees",
    description: "Government scale ERP with GPS geofencing and real time attendance.",
    stack: ["Next.js", "Supabase", "Pusher"],
    solo: true,
    untold: false,
    pattern: "pattern-dpmums",
    monogram: "DP",
    problem: "Attendance across 8 geographical districts was tracked manually on paper sheets, resulting in a three week processing cycle for monthly payroll.",
    decision: "Engineered a low bandwidth synchronization protocol with GPS geofencing and photographic validation, designed specifically for unstable 2G networks.",
    outcome: "Optimized administrative payroll cycles from three weeks to three hours for 152 regional personnel at zero infrastructure cost.",
    connections: {
      tech: ["01", "08"],
      problem: ["05", "09"],
      outcome: ["05"],
    },
  },
  {
    id: "04",
    title: "Reports Automation",
    slug: "reports-automation",
    tier: 1,
    status: "PRODUCTION",
    metric: "v102 stable",
    description: "Autonomous field reporting engine delivering role based HTML dashboards.",
    stack: ["Apps Script", "Gmail API", "Webhooks"],
    solo: true,
    untold: true,
    pattern: "pattern-reports",
    monogram: "RA",
    problem: "Operations relied on field personnel sending updates via chat apps, requiring managers to manually aggregate progress reports daily.",
    decision: "Automated the entire lifecycle: data ingestion, schema validation, dynamic dashboard rendering, and role based email delivery.",
    outcome: "Deployed v102, which operates autonomously to deliver targeted, real time analytics to 13 distinct organizational roles.",
    connections: {
      tech: ["05", "06", "07", "09", "10"],
      problem: ["02", "05"],
      outcome: ["01", "02"],
    },
  },
  {
    id: "05",
    title: "Field Reporter",
    slug: "field-reporter",
    tier: 2,
    status: "FUNCTIONAL",
    metric: "8 districts",
    description: "T Fiber telecom workforce app with strict 3 phase engine.",
    stack: ["Apps Script", "Maps API", "Vanilla JS"],
    solo: true,
    untold: true,
    pattern: "pattern-field",
    monogram: "FR",
    problem: "A regional telecom project lacked structured real time operational visibility across its mobile field workforce in 8 districts.",
    decision: "Designed a location verified, three phase reporting pipeline (Check In, Progress Log, Check Out) deployed on highly scalable, zero cost architecture.",
    outcome: "Secured comprehensive coverage across 8 districts, establishing a robust operational blueprint for distributed resource tracking.",
    connections: {
      tech: ["04", "06", "07", "09", "10"],
      problem: ["03", "04"],
      outcome: ["03", "04"],
    },
  },
  {
    id: "06",
    title: "Vantage OS",
    slug: "vantage-os",
    tier: 2,
    status: "FUNCTIONAL",
    metric: "3 contexts",
    description: "Multi context finance tracker with Udhaar debt splitting logic.",
    stack: ["React", "Firebase", "Apps Script"],
    solo: true,
    untold: false,
    pattern: "pattern-vantage",
    monogram: "VO",
    problem: "Standard financial trackers fail to separate multi entity finances, specifically across personal, family business, and technical project boundaries.",
    decision: "Built a multi context ledger featuring customized ledger splitting that mirrors traditional informal credit dynamics.",
    outcome: "Engineered clear separation of three financial contexts with relational debt structures modeled after family cash flows.",
    connections: {
      tech: ["04", "05", "07", "09", "10"],
      problem: ["01"],
      outcome: [],
    },
  },
  {
    id: "07",
    title: "Span Finder Pro",
    slug: "span-finder-pro",
    tier: 2,
    status: "FUNCTIONAL",
    metric: "0.005 deg precision",
    description: "Geospatial telecom infra lookup with tile based spatial indexing.",
    stack: ["Apps Script", "Leaflet", "GeoJSON"],
    solo: true,
    untold: false,
    pattern: "pattern-span",
    monogram: "SF",
    problem: "Retrieving local telecom infrastructure coordinates historically required extensive manual coordination, taking up to 48 hours.",
    decision: "Implemented a tile based geospatial indexing system on an interactive map with 0.005 degree precision to query towers instantly.",
    outcome: "Reduced infrastructure lookup time from 48 hours to under 2 seconds, empowering field teams to execute without delay.",
    connections: {
      tech: ["04", "05", "06", "09", "10"],
      problem: ["05"],
      outcome: ["05"],
    },
  },
  {
    id: "08",
    title: "GlobusIT ERP",
    slug: "globus-erp",
    tier: 3,
    status: "IN DEVELOPMENT",
    metric: "Task intent engine",
    description: "Internal organizational platform with hierarchical org chart logic.",
    stack: ["Next.js", "Prisma", "TanStack"],
    solo: true,
    untold: false,
    pattern: "pattern-erp",
    monogram: "GI",
    problem: "Legacy administrative operations suffered from siloed systems, static PDF org charts, and manual task delegation channels.",
    decision: "Architected a relational task intent system that maps responsibilities programmatically based on active roles, hierarchies, and contexts.",
    outcome: "Consolidates four legacy administration channels into a unified portal with embedded hierarchical user permissions.",
    connections: {
      tech: ["01", "03"],
      problem: ["09"],
      outcome: ["09"],
    },
  },
  {
    id: "09",
    title: "BSEC Recruitment",
    slug: "bsec-recruitment",
    tier: 3,
    status: "FUNCTIONAL",
    metric: "64 positions placed",
    description: "Relational CRM built on Google Sheets, now migrating to Next.js.",
    stack: ["Apps Script", "Bootstrap"],
    solo: true,
    untold: false,
    pattern: "pattern-bsec",
    monogram: "BS",
    problem: "Candidate pipelines were managed across disparate sheets, leading to data loss and limited visibility into recruitment stages.",
    decision: "Designed an agile relational CRM database within existing spreadsheet infrastructure to immediately establish pipeline monitoring.",
    outcome: "Enabled the placement of 64 positions while providing comprehensive recruitment stage visibility, establishing the foundation for a Next.js portal migration.",
    connections: {
      tech: ["04", "05", "06", "07", "10"],
      problem: ["03", "08"],
      outcome: ["08"],
    },
  },
  {
    id: "10",
    title: "Script Collection",
    slug: "utility-collection",
    tier: 4,
    status: "ARCHIVE",
    metric: "Foundational",
    description: "Provenance archive of the original scripts that started it all.",
    stack: ["Apps Script", "Python"],
    solo: true,
    untold: true,
    pattern: "pattern-scripts",
    monogram: "SC",
    problem: "Early technical scripts and automation utilities represent the foundation of mature production grade products.",
    decision: "Maintained a secure archive of early automation utilities, documenting initial solutions to operational gaps.",
    outcome: "These initial scripts formed the logical architectural layer for subsequent enterprise scale products.",
    connections: {
      tech: ["04", "05", "06", "07", "09"],
      problem: ["02"],
      outcome: [],
    },
  },
];

export const techStack = [
  { name: "Apps Script", count: 6 },
  { name: "Next.js", count: 3 },
  { name: "React", count: 2 },
  { name: "Firebase", count: 1 },
  { name: "Prisma", count: 1 },
  { name: "Sanity", count: 1 },
  { name: "Supabase", count: 1 },
  { name: "Pusher", count: 1 },
  { name: "Gemini", count: 1 },
  { name: "Razorpay", count: 1 },
  { name: "Gmail API", count: 1 },
  { name: "Webhooks", count: 1 },
  { name: "Maps API", count: 1 },
  { name: "Leaflet", count: 1 },
  { name: "GeoJSON", count: 1 },
  { name: "Bootstrap", count: 1 },
  { name: "Python", count: 1 },
  { name: "Mermaid.js", count: 1 },
  { name: "Vanilla JS", count: 1 },
  { name: "TanStack", count: 1 },
];

export const timeline = [
  { phase: "The Spark", date: "Early 2024", desc: "Initial scripts and automation workflows to solve manual data collections.", projects: 2 },
  { phase: "The Proof", date: "Mid 2024", desc: "Reliable automation platforms proving operational scaling.", projects: 4 },
  { phase: "Product Thinking", date: "Late 2024", desc: "Shifting standalone solutions to highly cohesive, productized architectures.", projects: 6 },
  { phase: "The Scale", date: "Early 2025", desc: "Deploying enterprise grade applications at scale.", projects: 8 },
  { phase: "Now", date: "2025", desc: "Architecting zero overhead, high reliability digital systems.", projects: 10 },
];

export const personalInfo = {
  name: "Anvith Reddy Rondla",
  title: "Junior Product Manager designing, engineering, and deploying high impact digital systems.",
  location: "Hyderabad, India",
  email: "anvithreddy.rondla@gmail.com",
  linkedin: "#",
  github: "#",
  twitter: "#",
  currently: {
    building: "DPMUMS v1.0: GPS geofencing and real time attendance",
    reading: "Building High Growth Products",
    thinking: "AI Agents for Field Operations",
    lastDeploy: "Reports Automation v102",
  },
  stats: {
    products: 10,
    states: 2,
    infraCost: "Zero",
    teamSize: 0,
    employeesTracked: 152,
    positionsPlaced: 64,
    districts: 8,
    orgChartRoles: 13,
    pingsPerMonth: "1.2M+",
    latestVersion: 102,
    aiTemplates: 14,
  },
  philosophy: [
    "Every system I deliver is anchored by a rigorous Business Requirements Document (BRD), ensuring complete operational alignment and strategic clarity.",
    "I believe in high impact skill acquisition, mastering modern frameworks like Next.js by engineering production grade state government platforms.",
    "I leverage artificial intelligence as an efficiency accelerator to scale execution while maintaining deep critical thought and robust engineering design.",
    "Every architecture and codebase I have deployed continues to run sustainably in active production environments.",
  ],
  story: [
    "I started at GlobusIT as a Data Analyst, where I observed critical operational bottlenecks: field personnel compiled field metrics via unstructured communication channels, leading to hours of manual aggregation daily.",
    "Recognizing the opportunity for automation, I designed and deployed a robust, low bandwidth data pipeline to orchestrate operations autonomously, with zero initial operational overhead.",
    "Following the measurable efficiency gains, I was promoted to Junior Product Manager in under two months, subsequently leading the architecture and delivery of ten production ready enterprise systems.",
    "I continue to design, build, and deploy resilient digital systems to solve real world problems.",
  ],
};
